openapi: 3.0.3
info:
  title: Calculator Service
  description: HTTP service for adding numbers, a goa teaser
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /swagger.json:
    get:
      tags:
      - openapi
      summary: Download ../../gen/http/openapi.json
      operationId: openapi#/swagger.json
      responses:
        "200":
          description: File downloaded
components: {}
